npingler: npins: lockfile version 7 -> 8
```
Error: Failed to deserialize sources.json

Caused by:
    Version 7 is too old, you need to run upgrade
Error:   × Failed to upgrade `npins` in /Users/wiggles/.config/npingler
  ╰─▶ `npins` failed: exit status: 1
      Command failed: `cd /Users/wiggles/.config/npingler && npins update --verbose`

$ npins upgrade
[INFO ] Replacing default.nix with an up to date version
[INFO ] Upgrading lock file to the newest format version
[INFO ] Upgrading to v8
[WARN ] Tarball pins dropped support for the "Lockable HTTP Tarball Protocol". Instead, locking and updating is now implemented through HTTP redirects. In most relevant setups, which should be a drop-in replacement with no further action needed. However, you are advised to inspect all pins of type `Url` and `Mutable` url (formerly `Tarball`) after the upgrade.
[WARN ] Tarball pins that may need manual inspection in this lock file: []
[INFO ] Upgrade complete
[INFO ] Done. It is recommended to at least run `npins update --partial` afterwards.

$ npins update --partial
[npingler] No Changes
[nixpkgs] No Changes
Updated 2/2 pins
[INFO ] Update successful.
```